[package]
name = "vqf"
description = "Implementation of the Versatile Quaternion-based Filter (VQF) algorithm for sensor fusion."
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
